image: Visual Studio 2017

platform:
  - x64
skip_branch_with_pr: false
cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn test
  - yarn rwin

test: off

on_failure:
  - curl -s https://report.ci/annotate.py | python - --tool msvc --input build.log

on_finish:
  # Framework with autodetection
  - curl -s https://report.ci/upload.py | python
