image: Visual Studio 2017

branches:
  only:
    - master
    - greenkeeper/initial

platform:
  - x64
skip_branch_with_pr: true
cache:
  - node_modules
  - '%USERPROFILE%\.electron'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - yarn

build_script:
  - yarn rwin

test: off
